//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NovaCore.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NovaCore.Web.Resources.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP/1.1 {0} {1}.
        /// </summary>
        internal static string ClientResponseHeader {
            get {
                return ResourceManager.GetString("ClientResponseHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while serving : {0}.
        /// </summary>
        internal static string ErrorServing {
            get {
                return ResourceManager.GetString("ErrorServing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got Client {0}.
        /// </summary>
        internal static string GotClient {
            get {
                return ResourceManager.GetString("GotClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} : Got request {1}.
        /// </summary>
        internal static string GotRequest {
            get {
                return ResourceManager.GetString("GotRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lost Client {0}.
        /// </summary>
        internal static string LostClient {
            get {
                return ResourceManager.GetString("LostClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Stream has exceeded the {0} limit specified..
        /// </summary>
        internal static string StreamException {
            get {
                return ResourceManager.GetString("StreamException", resourceCulture);
            }
        }
    }
}
